name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      backend_tag:
        description: 'Backend Docker image tag'
        required: false
        default: 'latest'
      frontend_tag:
        description: 'Frontend Docker image tag'
        required: false
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}

      - name: Add Azure VM to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Create deployment directory and set permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            mkdir -p ~/ecommerce-deploy
            sudo usermod -aG docker $USER
            sudo chown -R $USER:$USER ~/ecommerce-deploy

      - name: Create .env file
        run: |
          cat << 'EOF' > .env
          BACKEND_IMAGE=dilzhan/ecommerce-backend:${{ github.event.inputs.backend_tag || 'latest' }}
          FRONTEND_IMAGE=dilzhan/ecommerce-frontend:${{ github.event.inputs.frontend_tag || 'latest' }}
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          TOKEN_SECRET_KEY=${{ secrets.TOKEN_SECRET_KEY }}
          TOKEN_EXPIRY=${{ secrets.TOKEN_EXPIRY }}
          SMS_CONTACT_LIST_ID=${{ secrets.SMS_CONTACT_LIST_ID }}
          SMS_API_TOKEN=${{ secrets.SMS_API_TOKEN }}
          SMS_API_URL=${{ secrets.SMS_API_URL }}
          ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}
          REACT_APP_API_URL=${{ secrets.BACKEND_URL }}
          COOKIE_DOMAIN=${{ secrets.COOKIE_DOMAIN }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          EOF

      - name: Copy files to Azure VM
        run: |
          # Ensure proper line endings
          sed -i 's/\r$//' .env
          scp -o StrictHostKeyChecking=no docker-compose.yml .env ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }}:~/ecommerce-deploy/

      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          envs: DOCKERHUB_USERNAME,DOCKERHUB_TOKEN
          script: |
            cd ~/ecommerce-deploy
            # Fix any potential line ending issues
            sed -i 's/\r$//' .env
            
            # Login to Docker Hub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            # Ensure docker permissions
            sudo systemctl restart docker
            
            # Pull and restart containers
            sudo docker-compose pull
            sudo docker-compose down --remove-orphans
            sudo docker system prune -af
            sudo docker-compose up -d
            
            # Logout from Docker Hub for security
            sudo docker logout

      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd ~/ecommerce-deploy
            # Check if containers are running
            sudo docker-compose ps
            # Check container logs for any immediate errors
            sudo docker-compose logs --tail=50 